#!/usr/bin/env python3
"""Print the SLO dashboard summary for GitHub Actions step summary.

Reads slo-reports/slo_report.json (generated by scripts/slo_aggregator.py)
and prints a compact markdown summary suitable for appending to
$GITHUB_STEP_SUMMARY.

Extracted from an inline ``python -c`` block that was previously embedded in
.github/workflows/live-tests.yml — inline multi-line python strings in YAML
``run: |`` blocks inherit indentation and raise ``IndentationError``, silently
breaking the step while the aggregator itself succeeded.
"""

import json
import sys
from pathlib import Path


def main() -> int:
    report_path = Path("slo-reports/slo_report.json")
    if not report_path.exists():
        print("No SLO report generated")
        return 0

    with open(report_path) as f:
        report = json.load(f)

    print(f"**Overall Status:** `{report['overall_status'].upper()}`")
    print()
    print("### 7-Day SLO")
    slo7 = report.get("slo_7d", {})
    print(f"- Status: `{slo7.get('status', 'unknown').upper()}`")
    print(f"- Search Success: **{slo7.get('search', {}).get('success_rate', 'N/A')}%**")
    print(f"- Fetch Success: **{slo7.get('fetch', {}).get('success_rate', 'N/A')}%**")
    print(f"- Search P95: {slo7.get('search', {}).get('latency_p95_ms', 'N/A')}ms")
    print()
    print("### 30-Day SLO")
    slo30 = report.get("slo_30d", {})
    print(f"- Status: `{slo30.get('status', 'unknown').upper()}`")
    print(f"- Search Success: **{slo30.get('search', {}).get('success_rate', 'N/A')}%**")
    print(f"- Fetch Success: **{slo30.get('fetch', {}).get('success_rate', 'N/A')}%**")
    print(f"- Search P95: {slo30.get('search', {}).get('latency_p95_ms', 'N/A')}ms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
